const categories = {
	/* Overrides for products that may be inappropriately
	   caught by the tags below */
	'Groceries': [
		'vinegar',
	],

	/* F&F and other clothing */
	'Clothing': [
		'aw15',
		'aw16',
		'aw17',
		'aw18',
		'aw19',
		'aw20',
		'aw21',
		'aw22',
		'aw23',
		'aw24',
		'cnty',
		'f&f',
		'ss15',
		'ss16',
		'ss17',
		'ss18',
		'ss19',
		'ss20',
		'ss21',
		'ss22',
		'ss23',
		'ss24',
	],
	/* Household consumables (incl flowers) */
	'Household': [
		'alstroemeria',
		'ariel',
		'bag for life',
		'bouquet',
		'brita',
		'cling film',
		'colour catcher',
		'cushelle',
		'detergent',
		'dettol',
		'dishwasher',
		'dozen roses',
		'duracell',
		'energizer',
		'fairy ',
		'febreze',
		'go create',
		'handwash',
		'hg ',
		'kitchen foil',
		'kitchen towel',
		'kleenex',
		' led ',
		'lenor',
		'luxury roses',
		'pledge',
		'raid ',
		'sharpie',
		'spontex',
		'tissue',
		'toilet roll',
		'viakal',
		'vileda',
		'wagtastic',
		'washing pods',
		'washing up',
		'wham ',
	],
	/* Personal hygiene products */
	'Hygiene': [
		'argan oil',
		'aveeno',
		'bacterial',
		'body wash',
		'bodyform',
		'bubble bath',
		'burt\'s bees',
		'dove',
		'free spirit',
		'gillette',
		'handwash',
		'huggies',
		'imperial leather',
		'incontinence',
		'micellar',
		'nivea',
		'ogx',
		'oral-b',
		'pampers',
		'pantene',
		'sanex',
		'sensodyne',
		'shampoo',
		'shave ',
		'tena',
		'vaseline',
		'wipes',
	],
	/* Medication & supplements */
	'Health': [
		'abidec',
		'antiseptic',
		'bronchostop',
		'calpol',
		'canesten',
		'compeed',
		'cough syrup',
		'eczema',
		'face covering',
		' flu ',
		'glucosamine',
		'ibuprofen',
		'max strength',
		'multivitamin',
		'paracetamol',
		'strepsils',
		'wound',
		'zantac',
		'zovirax',
	],
	/* Durable household objects */
	'Home': [
		'bucket',
		'cable',
		'command',
		'dehumidifier',
		'diffuser',
		'dish brush',
		'extension lead',
		'foodsavers',
		'fox & ivy',
		'go cook',
		'lego',
		'pyrex',
		's/s',
		'squeegee',
		'storage',
		'toilet brush',
		'tommee tippee',
		'vase',
		'wd40',
		'white board',
	],
	/* Human-consumable alcoholic drinks */
	'Alcohol': [
		'% vol',
		'70cl',
		'75cl',
		'alcopops',
		'amstel',
		'baileys',
		'beer',
		'chambord',
		'champagne',
		'chardonnay',
		'cider',
		'havana club',
		' ipa ',
		'kopparberg',
		'liqueur',
		'malibu',
		'merlot',
		'rekorderlig',
		'sauvignon',
		'schnapps',
		'wine route',
	],
	/* Human-consumable cancer */
	'Tobacco': [
		'amber leaf',
		'benson & hedges',
		'cigarettes',
		'cigars',
		'cutters choice',
		'dunhill',
		'gold leaf',
		'golden virginia',
		'lambert & butler',
		'marlboro',
		'pall mall',
		'players ',
		'richmond green',
		'riverstone',
		'rizla',
		'rothmans',
		'silk cut ',
		'sovereign blue',
		'tobacco',
	],
	/* Car products */
	'Car': [
		'adblue',
		'redex',
		'screenwash',
	],
	/* Car fuel */
	'Fuel': [
		'diesel',
		'petrol',
	],
};

export default function(productName) {
	const name = String(productName).toLowerCase();

	const category = Object.keys(categories).find(category => {
		return categories[category].some(keyword => name.includes(keyword));
	});

	return category || 'Groceries';
};
